# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

boxes = [
  {
    :name => "ubuntu-1404-docker",
    :box => "ubuntu/trusty64",
    :ip => '192.168.100.200',
    :cpu => "50",
    :ram => "4096",
    :hostname => "docker-host",
    :gui => false,
    :shell_path => "provisioning/bash/provision.sh"
  }
]

  #Setup VM.
Vagrant.configure("2") do |config|
    boxes.each do |box|
        config.vm.define box[:name] do |vms|
            vms.vm.hostname = box[:hostname]
            vms.vm.box = box[:box]
            vms.vm.network :private_network, ip: box[:ip]

            config.vm.provider "virtualbox" do |vb|
                # Display the VirtualBox GUI when booting the machine
                vb.gui = box[:gui]
                vb.customize ["modifyvm", :id,"--cpuexecutioncap", box[:cpu]]
                vb.customize ["modifyvm", :id, "--memory", box[:ram]]
            end

            vms.vm.provision "shell" do |s|
	    	s.path = box[:shell_path]
	    	s.args = box[:hostname]
            end
        end
    end

end
